<link rel="stylesheet" href="../../../web/css/news.css">
<?php /** @var NewsModule\News\Block\Index\Index $block */ ?>
<?php $articleCollection = $block->getCollection(); ?>
<?php if (count($articleCollection)) { ?>
    <h1><?= $block->escapeHtml(__('Posts')) ?></h1>
    <?php foreach($block->getCollection() as $post): ?>
        <div class="post-container">
            <div class="post-img"></div>
            <div class="post-inner-container">
                <h2 class="post-name"><a href="#"><?php echo $post->getName(); ?></a></h2>
                <p class="post-content"><?php echo $post->getContent(); ?></p>
            </div>
        </div>
    <?php endforeach; ?>
<?php } ?>
